// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import ClientHeader from "@/app/components/ClientHeader";
import Footer from "@/app/components/Footer";
import common from "@/public/en/common.json";
import ConditionalHeader from "@/app/components/ConditionalHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`antialiased`}>
        <div className="flex flex-col">
          <div className="flex flex-col lg:flex-row">
            <aside className="lg:w-3/5 bg-white">
              <ConditionalHeader />
            </aside>
            <div className="flex-row py-[0rem] py-0 sm:py-[5rem] lg:py-[0rem]">
              <main className="flex-1">{children}</main>
              {/* <Footer /> */}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
