// app/ja/layout.js

import dynamic from "next/dynamic";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Footer from "@/app/components/Footer";
import common from "@/public/ja/common.json";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-col ">
      <div className="flex flex-col lg:flex-row">
        <div className="flex-row py-[2rem] lg:py-[0rem]">
          <main className="flex-1 mt-[4rem]  sm:mt-[6rem] lg:mt-[4.5rem]">
            {children}
          </main>
          {/* <Footer /> */}
        </div>
      </div>
    </div>
  );
}
