import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import common from "@/public/ja/common.json";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={`antialiased`}>
        <div className="flex flex-col ">
          <div className="flex flex-col lg:flex-row">
            <aside className="lg:w-2/5 bg-white">
              <Header common={common} />
            </aside>
            <div className="flex-row py-[2rem] lg:py-[0rem]">
              <main className="flex-1 mt-[4rem]  sm:mt-[6rem] lg:mt-[4.5rem]">
                {children}
              </main>
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
